FROM ruby:2.6.1

ENV BUNDLER_VERSION=2.0.2
# install rails dependencies
RUN apt-get clean all && apt-get update -qq && apt-get install -y build-essential libpq-dev \
    curl gnupg2 apt-utils default-libmysqlclient-dev git mysql-server libcurl3-dev cmake \
    libssl-dev pkg-config openssl imagemagick file nodejs 

RUN gem install bundler -v 2.0.2

WORKDIR /rails-backend

# Adding gems
COPY Gemfile Gemfile.lock ./
# ADD Gemfile.lock /rails-backend-prod/Gemfile.lock
# RUN gem install bundler

RUN bundle check || bundle install

COPY . ./

EXPOSE 3000


CMD ["rails", "s"]

# SOMEWHERE HERE RUN DB CREATE< MIGRATE *****


# Add a script to be executed every time the container starts.
# COPY /config/environment.rb /usr/bin/
# RUN chmod +x /usr/bin/environment.rb
# ENTRYPOINT ["environment.rb"]
